param([switch]$Portable)
$ErrorActionPreference="Stop";$ProjectRoot=Split-Path -Parent $MyInvocation.MyCommand.Path;Set-Location -LiteralPath $ProjectRoot
function Write-Step([string]$m){Write-Host "";Write-Host "==> $m" -ForegroundColor Cyan}
function Find-Python312{$ls=@(@{File="py";Args=@("-3.12")},@{File="$env:LOCALAPPDATA\Programs\Python\Python312\python.exe";Args=@()},@{File="C:\Program Files\Python312\python.exe";Args=@()});foreach($e in $ls){try{$v=& $e.File @($e.Args) -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>$null;if($LASTEXITCODE-eq 0-and$v-eq"3.12"){return $e}}catch{}};return $null}
Write-Host "Ember v0.2 Windows Installer" -ForegroundColor Magenta
if($Portable){Write-Host "Portable mode: Ember's runtime, memory, configuration, logs, and model cache stay with this folder.";$env:HF_HOME=Join-Path $ProjectRoot ".cache\huggingface";$env:XDG_CACHE_HOME=Join-Path $ProjectRoot ".cache";New-Item -ItemType Directory -Force -Path $env:HF_HOME|Out-Null}
$Python=Find-Python312;if($null-eq$Python){Write-Step "Installing Python 3.12";$w=Get-Command winget -ErrorAction SilentlyContinue;if($null-eq$w){throw "Python 3.12 is required for setup and Winget is unavailable."};& winget install --id Python.Python.3.12 --exact --scope user --accept-package-agreements --accept-source-agreements --silent;if($LASTEXITCODE-ne 0){throw "Could not install Python 3.12."};$Python=Find-Python312;if($null-eq$Python){throw "Restart Windows and run setup again."}}
function Invoke-Python312([string[]]$a){& $Python.File @($Python.Args) @a;if($LASTEXITCODE-ne 0){throw "Python command failed."}}
Write-Step "Creating Ember's application environment";if(-not(Test-Path ".venv\Scripts\python.exe")){Invoke-Python312 @("-m","venv",".venv")};& ".venv\Scripts\python.exe" -m pip install --upgrade pip;& ".venv\Scripts\python.exe" -m pip install -r requirements.txt;if($LASTEXITCODE-ne 0){throw "Could not install Ember dependencies."}
Write-Step "Creating Ember's Chatterbox voice environment";if(-not(Test-Path ".chatterbox_venv\Scripts\python.exe")){Invoke-Python312 @("-m","venv",".chatterbox_venv")};& ".chatterbox_venv\Scripts\python.exe" -m pip install --upgrade pip;& ".chatterbox_venv\Scripts\python.exe" -m pip install chatterbox-tts sounddevice soundfile;if($LASTEXITCODE-ne 0){throw "Could not install Chatterbox."};if($null-ne(Get-Command nvidia-smi -ErrorAction SilentlyContinue)){& ".chatterbox_venv\Scripts\python.exe" -m pip install --force-reinstall "torch==2.6.0+cu126" "torchaudio==2.6.0+cu126" --index-url https://download.pytorch.org/whl/cu126;if($LASTEXITCODE-ne 0){throw "Could not install CUDA-enabled PyTorch for Chatterbox."}}
Write-Step "Creating local configuration";if(-not(Test-Path ".env")){Copy-Item ".env.example" ".env"};if(-not(Test-Path "config.json")){Copy-Item "config.example.json" "config.json"};if(-not(Test-Path "youtube_library.json")){Set-Content "youtube_library.json" "[]" -Encoding UTF8}
if($Portable){$c=Get-Content "config.json" -Raw|ConvertFrom-Json;$c|Add-Member -NotePropertyName portable_mode -NotePropertyValue $true -Force;$c.chatterbox_python=".chatterbox_venv\Scripts\python.exe";$c|ConvertTo-Json -Depth 20|Set-Content "config.json" -Encoding UTF8;Set-Content ".portable" "Ember portable installation" -Encoding UTF8}
Write-Step "Creating Ember launcher";$launcher=@('@echo off','setlocal','title Ember','cd /d "%~dp0"','if exist ".portable" (',' set "HF_HOME=%CD%\.cache\huggingface"',' set "XDG_CACHE_HOME=%CD%\.cache"',')','if not exist ".venv\Scripts\python.exe" (',' echo Ember is not installed yet.',' pause',' exit /b 1',')','".venv\Scripts\python.exe" ember_app.py','if errorlevel 1 pause');Set-Content "run_ember.bat" $launcher -Encoding ASCII
Write-Step "Checking the installation";& ".venv\Scripts\python.exe" -m py_compile ember_app.py dashboard_server.py game_events.py memory_store.py spotify_control.py wow_pixel_bridge.py ember\__init__.py ember\core.py ember\embodiment.py ember\overlay.py ember\telemetry.py ember\diagnostics.py;if($LASTEXITCODE-ne 0){throw "Ember Python validation failed."};& ".venv\Scripts\python.exe" -c "from ember import WorldState; from ember.diagnostics import evaluate_blood_elf_observation; assert not evaluate_blood_elf_observation({'game':'World of Warcraft'}).passed; print('Ember v0.2 core ready')";if($LASTEXITCODE-ne 0){throw "Ember core self-test failed."}
Write-Host "";Write-Host "Installation complete." -ForegroundColor Green;if($Portable){Write-Host "Portable Ember is ready." -ForegroundColor Green};Write-Host "Add your OpenAI API key to .env, then run run_ember.bat."
